--DDL 
--********************************************************************-- 
--author:柳彬 
--create time:2025-01-23 14:06:34 
--********************************************************************--
DROP TABLE
  IF EXISTS ODS_HBCORE_GGCLAUSE_2;

CREATE TABLE
  IF NOT EXISTS ODS_HBCORE_GGCLAUSE_1 (
    CLAUSECODE STRING,
    CLAUSECNAME STRING,
    CLAUSETNAME STRING,
    CLAUSEENAME STRING,
    LANGUAGE STRING,
    RISKCLASS STRING,
    CREATORCODE STRING,
    CREATETIME TIMESTAMP,
    UPDATERCODE STRING,
    UPDATETIME TIMESTAMP,
    VALIDDATE TIMESTAMP,
    INVALIDDATE TIMESTAMP,
    VALIDIND STRING,
    REMARK STRING,
    FLAG STRING,
    READONLYIND STRING,
    CLAUSELONGCNAME STRING,
    CLAUSELONGTNAME STRING,
    CLAUSELONGENAME STRING,
    ETL_DATE TIMESTAMP COMMENT '数仓更新时间'
  ) COMMENT '条款信息表' ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' LINES TERMINATED BY '\n' STORED AS TEXTFILE;